### ISSUE TITLE
[Test_UART] Протокол передачи данных управления сервами

### ISSUE THREAD

**Issue by KaiL4eK** [Shnuer/TiltCV#1]
Для передачи сервам задания с GUI необходимо продумать протокол передачи (формат фрейма) и реализовать его работу в коде МК

**Comment by KaiL4eK** [comment]
По последнему обсуждению:
Фрейм задания скважности:

Размер | Назначение | Типовое значение
-----------|-------------------|-----------------------
1           | Начало фрейма          | Символ `#` (ASCII = 35)
1           | Номер сервопривода | Значение 1 или 2
2           | Скважность ШИМ       | -

**Comment by Shnuer** [comment]
думаю этот тикет, можно закрыть)
